name: Checkmarx One Scan
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx One CLI Action
        uses: Checkmarx/ast-github-action@2.0.23
        with:
          project_name:  ${{ github.repository }}
          cx_tenant: ${{ vars.CX_TENANT }}
          base_uri: ${{ vars.BASE_URI }} 
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
  
  
